/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hagi' at '16/08/30 23:54' with Gradle 3.0
 *
 * @author hagi, @date 16/08/30 23:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
